CREATE SEQUENCE Secu_Rol
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_bitacora_visita
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Estado
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Ciudad
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Religion
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Educacion
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Hobby
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_tipo_bebedor
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_color_ojos
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_contextura
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_UsuarioXEvento
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_ActividadXUsuario
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Estado_Civil
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_actividadAL
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_pais
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_ocupacion
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_evento
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_color_piel
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_estado_match
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_interes_gusto
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_UsuariosXmatch
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_UsuarioXIdioma
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_UsuarioXOcupacion
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Usuario
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_signo_zodiacal
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Bitacora_Conocidos
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_wink
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Estilo_Vida
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Tipo_Pareja
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Aspecto_Fisico
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Color_Pelo
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_HobbyXUsuario
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE secu_Idioma
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;